name: Odoo 18 CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: odoo
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git python3-pip build-essential wget node-less libpq-dev
          pip install wheel setuptools
          pip install -r https://github.com/odoo/odoo/raw/18.0/requirements.txt

      - name: Run Odoo tests
        run: |
          git clone --depth 1 --branch 18.0 https://www.github.com/odoo/odoo odoo
          python3 odoo/odoo-bin --addons-path=odoo/addons,./my_module -d test_db --test-enable --stop-after-init --log-level=test
